---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  remote_user: vagrant
  become: yes
  become_user: root

  roles:
    - docker
    - kubectl
    - awscli
    - hal
